<?php

/**
 * A unique identifier is defined to store the options in the database and reference them from the theme.
 * By default it uses the theme name, in lowercase and without spaces, but this can be changed if needed.
 * If the identifier changes, it'll appear as if the options have been reset.
 *
 */
function optionsframework_option_name() {

    // This gets the theme name from the stylesheet (lowercase and without spaces)
    $themename = get_option('stylesheet');
    $themename = preg_replace("/\W/", "_", strtolower($themename));

    $optionsframework_settings = get_option('optionsframework');
    $optionsframework_settings['id'] = $themename;
    update_option('optionsframework', $optionsframework_settings);

    // echo $themename;
}

/**
 * Defines an array of options that will be used to generate the settings page and be saved in the database.
 * When creating the 'id' fields, make sure to use all lowercase and no spaces.
 *
 */
function optionsframework_options() {

    $options = array();

    $options[] = array(
        'name' => __('General Settings', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('See More Text', 'options_check'),
        'id' => 'general_see_more_text',
        'std' => 'See More',
        'type' => 'text');

    $options[] = array(
        'name' => __('Learn More Text', 'options_check'),
        'id' => 'general_learn_more_text',
        'std' => 'Learn More',
        'type' => 'text');
    $options[] = array(
        'name' => __('Published on Text', 'options_check'),
        'id' => 'general_published_on_text',
        'std' => 'Published on:',
        'type' => 'text');

    $options[] = array(
        'name' => __('White Paper Text', 'options_check'),
        'id' => 'general_white_paper_text',
        'std' => 'White Paper',
        'type' => 'text');

    $options[] = array(
        'name' => __('Blog Text', 'options_check'),
        'id' => 'general_Blog_text',
        'std' => 'Blog',
        'type' => 'text');

    $options[] = array(
        'name' => __('Crosita site Blog Text', 'options_check'),
        'id' => 'general_hr_blog_text',
        'std' => 'Crosita site Blog Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Open Positions Text', 'options_check'),
        'id' => 'general_open_position_text',
        'std' => 'Open Positions',
        'type' => 'text');

    $options[] = array(
        'name' => __('Remote Text', 'options_check'),
        'id' => 'general_remote_text',
        'std' => 'Remote',
        'type' => 'text');

    $options[] = array(
        'name' => __('Freelance Text', 'options_check'),
        'id' => 'general_freelance_text',
        'std' => 'Freelance',
        'type' => 'text');
    
    
    $options[] = array(
        'name' => __('Career Filter Functions', 'options_check'),
        'id' => 'career_filter_functions',
        'std' => 'Functions',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Career Filter Experiences', 'options_check'),
        'id' => 'career_filter_experiences',
        'std' => 'Experiences',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Career Filter Locations', 'options_check'),
        'id' => 'career_filter_locations',
        'std' => 'Locations',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Career Filter Freelance', 'options_check'),
        'id' => 'career_filter_freelance',
        'std' => 'Freelance',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Career Filter Remote Work', 'options_check'),
        'id' => 'career_filter_remote_work',
        'std' => 'Remote Work',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Career Filter Clear Filters', 'options_check'),
        'id' => 'career_filter_clear_filters',
        'std' => 'Clear Filters',
        'type' => 'text');


    $options[] = array(
        'name' => __('Jobs Found', 'options_check'),
        'id' => 'jobs_found_text',
        'std' => 'Jobs Found',
        'type' => 'text');

    $options[] = array(
        'name' => __('Job Search Text', 'options_check'),
        'id' => 'general_job_search_text',
        'std' => 'Job Search',
        'type' => 'text');

    $options[] = array(
        'name' => __('View All Text', 'options_check'),
        'id' => 'general_view_all_text',
        'std' => 'View All',
        'type' => 'text');

    $options[] = array(
        'name' => __('More Jobs', 'options_check'),
        'id' => 'general_more_jobs_text',
        'std' => 'More Jobs',
        'type' => 'text');

    $options[] = array(
        'name' => __('About Heading Text', 'options_check'),
        'id' => 'general_heading_text',
        'std' => 'About Heading Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Team Text', 'options_check'),
        'id' => 'general_team_text',
        'std' => 'Team Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Find Text', 'options_check'),
        'id' => 'general_find_text',
        'std' => 'Find',
        'type' => 'text');

    $options[] = array(
        'name' => __('Go TO Text', 'options_check'),
        'id' => 'general_go_to_text',
        'std' => 'Go TO',
        'type' => 'text');
    $options[] = array(
        'name' => __('Go Text', 'options_check'),
        'id' => 'general_go_text',
        'std' => 'Go',
        'type' => 'text');

    $options[] = array(
        'name' => __('Employees', 'options_check'),
        'id' => 'general_employees_text',
        'std' => 'Employees',
        'type' => 'text');

    $options[] = array(
        'name' => __('Covid Button Text', 'options_check'),
        'id' => 'general_covid_button_text',
        'std' => 'Covid',
        'type' => 'text');

    $options[] = array(
        'name' => __('Regional Head', 'options_check'),
        'id' => 'general_regional_head_text',
        'std' => 'Regional Head',
        'type' => 'text');
    $options[] = array(
        'name' => __('Key Skills', 'options_check'),
        'id' => 'general_key_skils_text',
        'std' => 'Key Skills',
        'type' => 'text');
    $options[] = array(
        'name' => __('Job Opeings', 'options_check'),
        'id' => 'general_job_openings_text',
        'std' => 'Job Openings',
        'type' => 'text');
    $options[] = array(
        'name' => __('View Map', 'options_check'),
        'id' => 'general_view_map_text',
        'std' => 'View Map',
        'type' => 'text');

    $options[] = array(
        'name' => __('View Map Link', 'options_check'),
        'id' => 'general_viewmap_link',
        'std' => 'https://goo.gl/maps/P3nYGumULrcLhzYx5',
        'type' => 'text');

    $options[] = array(
        'name' => __('Related Content Heading', 'options_check'),
        'id' => 'general_related_content_heading',
        'std' => 'Related Content',
        'type' => 'text');

    $options[] = array(
        'name' => __('Services Testimonial Heading', 'options_check'),
        'id' => 'general_services_testimonial_heading',
        'std' => 'Meet Our Experts',
        'type' => 'text');

    $options[] = array(
        'name' => __('Read More Text', 'options_check'),
        'id' => 'general_read_more_text',
        'std' => 'Read More',
        'type' => 'text');
    $options[] = array(
        'name' => __('All Text', 'options_check'),
        'id' => 'general_all_text',
        'std' => 'All',
        'type' => 'text');
    $options[] = array(
        'name' => __('Load More Text', 'options_check'),
        'id' => 'general_load_more_text',
        'std' => 'Load More',
        'type' => 'text');
    $options[] = array(
        'name' => __('Loading Text', 'options_check'),
        'id' => 'general_loading_text',
        'std' => 'Loading',
        'type' => 'text');
    $options[] = array(
        'name' => __('Next Text', 'options_check'),
        'id' => 'general_next_text',
        'std' => 'Next',
        'type' => 'text');
    $options[] = array(
        'name' => __('Previous Text', 'options_check'),
        'id' => 'general_previous_text',
        'std' => 'Prev',
        'type' => 'text');
    $options[] = array(
        'name' => __('View Profile Text', 'options_check'),
        'id' => 'general_view_profile_text',
        'std' => 'View Profile',
        'type' => 'text');
    $options[] = array(
        'name' => __('Join Us Text', 'options_check'),
        'id' => 'general_join_us_text',
        'std' => 'Join Us',
        'type' => 'text');
    $options[] = array(
        'name' => __('Disclaimer Text', 'options_check'),
        'id' => 'general_disclaimer_text',
        'std' => 'Personal Information Disclaimer',
        'type' => 'text');

    $options[] = array(
        'name' => __('Common Message', 'options_check'),
        'id' => 'general_common_message',
        'std' => "If you haven't found what you're looking for please contact ....",
        'type' => 'text');
    $options[] = array(
        'name' => __('Cookies Law Message', 'options_check'),
        'id' => 'general_cookies_message',
        'std' => "We use cookies to provide you with a better on site experience. You can read more about our use of cookies in our <a href='/cookies-policy'>Cookies Policy</a>.<br>Click OK to continue browsing the GlobalLogic site.",
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Get In Touch', 'options_check'),
        'id' => 'get_in_touch',
        'std' => "Get In Touch",
        'type' => 'text');
    $options[] = array(
        'name' => __('Published', 'options_check'),
        'id' => 'published',
        'std' => "Published",
        'type' => 'text');

    $options[] = array(
        'name' => __('Contact Us', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Hero Title', 'options_check'),
        'id' => 'contact_hero_title',
        'std' => 'How can we help you?',
        'type' => 'text');
    $options[] = array(
        'name' => __('Content Title', 'options_check'),
        'id' => 'contact_content_title',
        'std' => 'Get in touch',
        'type' => 'text');

    $options[] = array(
        'name' => __('Form title 1', 'options_check'),
        'id' => 'form_title1',
        'std' => 'DON\'T BE SHY',
        'type' => 'text');
    $options[] = array(
        'name' => __('Form title 2', 'options_check'),
        'id' => 'form_title2',
        'std' => 'SEND US A MESSAGE',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Content Description', 'options_check'),
        'id' => 'contact_content_description',
        'std' => 'Whether you\'re searching for a new partner or a new career, we want to hear from you! Fill out the below form, and one of our team members will contact you shortly.',
        'type' => 'textarea');

    $options[] = array(
        'name' => __('Contact Thankyou text Description', 'options_check'),
        'id' => 'contact_thankyoutext_description',
        'std' => 'Thank you for your interest in GlobalLogic.',
        'type' => 'textarea');

    $options[] = array(
        'name' => __('Thankyou Description', 'options_check'),
        'id' => 'contact_thankyou_description',
        'std' => 'Thank you for your interest in GlobalLogic.',
        'type' => 'textarea');

    $options[] = array(
        'name' => __('Contact Information Text', 'options_check'),
        'id' => 'contact_info',
        'std' => 'Contact Information',
        'type' => 'text');

    /* address1 */

    $options[] = array(
        'name' => __('Contact Address1 Heading', 'options_check'),
        'id' => 'address1_heading',
        'std' => 'Corporate Headquarters',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address1 Details', 'options_check'),
        'id' => 'address1_details',
        'std' => '1095, Broken Sound Pkwy NW',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Contact Address1 View Map Text', 'options_check'),
        'id' => 'address1_view_map_text',
        'std' => 'View Map',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address1 View Map Link', 'options_check'),
        'id' => 'address1_viewmap_link',
        'std' => 'https://goo.gl/maps/P3nYGumULrcLhzYx5',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address1 Phone Text', 'options_check'),
        'id' => 'address1_phone_text',
        'std' => 'Contact Phone Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address1 Phone1', 'options_check'),
        'id' => 'address1_phone1',
        'std' => 'Contact Phone Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address1 Phone2', 'options_check'),
        'id' => 'address1_phone2',
        'std' => 'Contact Phone Text2',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address1 Email Text', 'options_check'),
        'id' => 'address1_email_text',
        'std' => 'Email Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address1 Email1', 'options_check'),
        'id' => 'address1_email1',
        'std' => 'Email Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address1 Email2', 'options_check'),
        'id' => 'address1_email2',
        'std' => 'info@globallogic.com',
        'type' => 'text');

    /* Address 2 */

    $options[] = array(
        'name' => __('Contact Address2 Heading', 'options_check'),
        'id' => 'address2_heading',
        'std' => 'Contact Information',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address2 Details', 'options_check'),
        'id' => 'address2_details',
        'std' => 'Boca Raton, Florida 33487',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('View Map Text', 'options_check'),
        'id' => 'address2_view_map_text',
        'std' => 'View Map',
        'type' => 'text');
    $options[] = array(
        'name' => __('View Map Link', 'options_check'),
        'id' => 'address2_viewmap_link',
        'std' => 'https://goo.gl/maps/P3nYGumULrcLhzYx5',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address2 Email Text', 'options_check'),
        'id' => 'address2_email_text',
        'std' => 'Email Text2',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address2 Email1', 'options_check'),
        'id' => 'address2_email1',
        'std' => 'Email Text2',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address2 Email2', 'options_check'),
        'id' => 'address2_email2',
        'std' => 'sales@globallogic.com',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address2 Phone Text', 'options_check'),
        'id' => 'address2_phone_text',
        'std' => 'Phone Number1',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address2 Phone1', 'options_check'),
        'id' => 'address2_phone1',
        'std' => 'Phone Number1',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact Address2 Phone2', 'options_check'),
        'id' => 'address_phone2',
        'std' => 'Phone Number2',
        'type' => 'text');
    $options[] = array(
        'name' => __('Responsible Heading', 'options_check'),
        'id' => 'responsible_heading',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name' => __('Responsible Description', 'options_check'),
        'id' => 'responsible_description',
        'std' => '',
        'type' => 'textarea');

    /* $options[] = array(
      'name' => __('Contact Address Title', 'options_check'),
      'id' => 'contact address_title',
      'std' => 'Contact Address Title',
      'type' => 'text');



      $options[] = array(
      'name' => __('Contact Address Text', 'options_check'),
      'id' => 'contact_address_text',
      'std' => 'Contact Address Text',
      'type' => 'text');

      $options[] = array(
      'name' => __('Phone', 'options_check'),
      'id' => 'contact_phone',
      'std' => 'phone',
      'type' => 'text');
     */







    $options[] = array(
        'name' => __('Breadcrumb', 'options_check'),
        'type' => 'heading');

    $options[] = array(
        'name' => __('Home Text', 'options_check'),
        'id' => 'breadcrumb_home_title',
        'std' => 'Home Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Careers Text', 'options_check'),
        'id' => 'breadcrumb_careers_title',
        'std' => 'Careers Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Job Listing Text', 'options_check'),
        'id' => 'breadcrumb_job_listing_title',
        'std' => 'Job Listing Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Job Detail Text', 'options_check'),
        'id' => 'breadcrumb_job_detail_title',
        'std' => 'Job Detail Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Papers Text', 'options_check'),
        'id' => 'breadcrumb_papers_title',
        'std' => 'Papers Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Blogs Text', 'options_check'),
        'id' => 'breadcrumb_blogs_title',
        'std' => 'Blogs Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Events Text', 'options_check'),
        'id' => 'breadcrumb_events_title',
        'std' => 'Events Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Case Studies Text', 'options_check'),
        'id' => 'breadcrumb_case_studies_title',
        'std' => 'Case Studies Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('Insights Text', 'options_check'),
        'id' => 'breadcrumb_insights_title',
        'std' => 'Insights Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('About', 'options_check'),
        'id' => 'breadcrumb_about_title',
        'std' => 'About Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Regional', 'options_check'),
        'id' => 'breadcrumb_regional_title',
        'std' => 'Regional Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Business Units', 'options_check'),
        'id' => 'breadcrumb_business_units_title',
        'std' => 'Business Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Leadership', 'options_check'),
        'id' => 'breadcrumb_leadership_title',
        'std' => 'Leadership Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Corporate', 'options_check'),
        'id' => 'breadcrumb_corporate_title',
        'std' => 'Corporate Text',
        'type' => 'text');

    $options[] = array(
        'name' => __('News', 'options_check'),
        'id' => 'breadcrumb_news_title',
        'std' => 'News Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Services', 'options_check'),
        'id' => 'breadcrumb_services_title',
        'std' => 'Services Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Digital Accelerators', 'options_check'),
        'id' => 'breadcrumb_digital_acc',
        'std' => 'Digital Accelerators',
        'type' => 'text');

    $options[] = array(
        'name' => __('Press Release', 'options_check'),
        'id' => 'breadcrumb_press_release_title',
        'std' => 'Press Release Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Media Coverage', 'options_check'),
        'id' => 'breadcrumb_media coverage_title',
        'std' => 'Media Coverage Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Award', 'options_check'),
        'id' => 'breadcrumb_award_title',
        'std' => 'Award Text',
        'type' => 'text');
	 $options[] = array(
        'name' => __('Key Projects', 'options_check'),
        'id' => 'breadcrumb_key-projects_title',
        'std' => 'Key Projects',
        'type' => 'text');	

    $options[] = array(
        'name' => __('Work With Us', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Content Title', 'options_check'),
        'id' => 'work_content_title',
        'std' => 'Join the Team',
        'type' => 'text');
    $options[] = array(
        'name' => __('Power Statement Text 1', 'options_check'),
        'id' => 'work_power_text_1',
        'std' => 'Four reasons',
        'type' => 'text');
    $options[] = array(
        'name' => __('Power Statement Text 2', 'options_check'),
        'id' => 'work_power_text_2',
        'std' => 'to call GlobalLogic home',
        'type' => 'text');
    $options[] = array(
        'name' => __('Form Title', 'options_check'),
        'id' => 'work_form_title',
        'std' => 'Your career starts here',
        'type' => 'text');
    $options[] = array(
        'name' => __('Form Button', 'options_check'),
        'id' => 'work_form_button',
        'std' => 'Find Jobs',
        'type' => 'text');
    $options[] = array(
        'name' => __('Country Text', 'options_check'),
        'id' => 'country_text',
        'std' => 'COUNTRY',
        'type' => 'text');
    $options[] = array(
        'name' => __('City Text', 'options_check'),
        'id' => 'city_text',
        'std' => 'CITY',
        'type' => 'text');
    $options[] = array(
        'name' => __('Role Text', 'options_check'),
        'id' => 'role_text',
        'std' => 'ROLE',
        'type' => 'text');

    $options[] = array(
        'name' => __('Footer', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Facebook Link', 'options_check'),
        'id' => 'footer_facebook_link',
        'std' => 'https://www.facebook.com/GlobalLogic/',
        'type' => 'text');
    $options[] = array(
        'name' => __('Twitter Link', 'options_check'),
        'id' => 'footer_twitter_link',
        'std' => 'https://twitter.com/globallogic',
        'type' => 'text');
    $options[] = array(
        'name' => __('Youtube Link', 'options_check'),
        'id' => 'footer_youtube_link',
        'std' => 'https://www.youtube.com/company/globallogic',
        'type' => 'text');
    $options[] = array(
        'name' => __('LinkedIn Link', 'options_check'),
        'id' => 'footer_linkedin_link',
        'std' => 'https://www.linkedin.com/company/globallogic',
        'type' => 'text');

    $options[] = array(
        'name' => __('Instagram Link', 'options_check'),
        'id' => 'footer_instagram_link',
        'std' => 'https://www.instagram.com/company/globallogic',
        'type' => 'text');
    $options[] = array(
        'name' => __('Telegram Link', 'options_check'),
        'id' => 'footer_telegram_link',
        'std' => 'https://t.me/gl_education',
        'type' => 'text');
    $options[] = array(
        'name' => __('Copyright Text', 'options_check'),
        'id' => 'footer_copyright_text',
        'std' => '2016 Copyright GlobalLogic. All rights reserved.',
        'type' => 'text');
    $options[] = array(
        'name' => __('Privacy Policy Text', 'options_check'),
        'id' => 'footer_privacy_text',
        'std' => 'Privacy Policy',
        'type' => 'text');
    $options[] = array(
        'name' => __('Cookies Law Text', 'options_check'),
        'id' => 'footer_cookie_text',
        'std' => 'Cookies Policy',
        'type' => 'text');
    $options[] = array(
        'name' => __('GDPR Text', 'options_check'),
        'id' => 'footer_gdpr_text',
        'std' => 'GDPR',
        'type' => 'text');
    $options[] = array(
        'name' => __('EU Recruitment Notice Text', 'options_check'),
        'id' => 'footer_eu_recruitment_notice',
        'std' => 'EU Recruitment Policy',
        'type' => 'text');
    $options[] = array(
        'name' => __('Terms Of Services Text', 'options_check'),
        'id' => 'footer_terms_text',
        'std' => 'Terms of Services',
        'type' => 'text');
    $options[] = array(
        'name' => __('Notice of Filling Text', 'options_check'),
        'id' => 'footer_notice_text',
        'std' => 'Notice of Filling',
        'type' => 'text');
    $options[] = array(
        'name' => __('Country Selector Text', 'options_check'),
        'id' => 'footer_country_selector',
        'std' => 'Select your country',
        'type' => 'text');
    $options[] = array(
        'name' => __('Modern Slavery Statement Text', 'options_check'),
        'id' => 'footer_modern_slavery_statement',
        'std' => 'Modern Slavery Statement Text',
        'type' => 'text');
    $options[] = array(
        'name' => __('Subscribe Form ID', 'options_check'),
        'id' => 'subscribe_form_id',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name' => __('Subscribe Form Thankyou page URL', 'options_check'),
        'id' => 'subscribe_form_thankyoupage_url',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name' => __('Subscribe Form Thankyou Content', 'options_check'),
        'id' => 'subscribe_form_thankyoupage_content',
        'std' => '',
        'type' => 'textarea');

    $options[] = array(
        'name' => __('Regional Sites', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Regional Sites', 'options_check'),
        'desc' => __('1 site per line. Format: Name | URL', 'options_check'),
        'id' => 'regional_sites',
        'std' => 'Global / English | http://www.glwebsite-new.globallogic.com',
        'type' => 'textarea');

    $options[] = array(
        'name' => __('404 Page Text Selector', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('404 Error Text', 'options_check'),
        'id' => 'error_404_text',
        'std' => "Oops, the page you're looking for does not exist.",
        'type' => 'text');
    $options[] = array(
        'name' => __('Return Home Text', 'options_check'),
        'id' => 'return_home_text',
        'std' => "Return Home",
        'type' => 'text');

    $options[] = array(
        'name' => __('Other Text Selector', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Corporate Text', 'options_check'),
        'id' => 'corporate_text',
        'std' => 'CORPORATE',
        'type' => 'text');
    $options[] = array(
        'name' => __('Regional Text', 'options_check'),
        'id' => 'regional_text',
        'std' => 'REGIONAL',
        'type' => 'text');
    $options[] = array(
        'name' => __('Global Regional Text', 'options_check'),
        'id' => 'global_regional_text',
        'std' => 'GLOBAL REGIONAL',
        'type' => 'text');
    $options[] = array(
        'name' => __('Business Unit Text', 'options_check'),
        'id' => 'business_unit_text',
        'std' => 'BUSINESS UNIT',
        'type' => 'text');
    $options[] = array(
        'name' => __('Board of Directors Text', 'options_check'),
        'id' => 'board_of_directors_text',
        'std' => 'BOARD OF DIRECTORS',
        'type' => 'text');

    $options[] = array(
        'name' => __('Go to Website Text', 'options_check'),
        'id' => 'goto_website_text',
        'std' => 'Go to the website',
        'type' => 'text');
    $options[] = array(
        'name' => __('Contact us Text', 'options_check'),
        'id' => 'contact_us_text',
        'std' => 'Contact us',
        'type' => 'text');
    $options[] = array(
        'name' => __('Engineering Centers Text', 'options_check'),
        'id' => 'engineering_centers_text',
        'std' => 'Engineering Centers',
        'type' => 'text');
    $options[] = array(
        'name' => __('Regional Offices Text', 'options_check'),
        'id' => 'regional_offices_text',
        'std' => 'Regional Offices',
        'type' => 'text');
    $options[] = array(
        'name' => __('Method Studios Text', 'options_check'),
        'id' => 'method_studios_text',
        'std' => 'Method Studios',
        'type' => 'text');
    $options[] = array(
        'name' => __('Cities Text', 'options_check'),
        'id' => 'cities_text',
        'std' => 'Cities',
        'type' => 'text');

    $options[] = array(
        'name' => __('More Cities Text', 'options_check'),
        'id' => 'more_cities_text',
        'std' => ' More Cities',
        'type' => 'text');
    $options[] = array(
        'name' => __('All Text', 'options_check'),
        'id' => 'all_text',
        'std' => ' All',
        'type' => 'text');

    $options[] = array(
        'name' => __('Apply for this job Text', 'options_check'),
        'id' => 'apply_for_this_job_text',
        'std' => 'Apply for this job',
        'type' => 'text');

    $options[] = array(
        'name' => __('Back to jobs Text', 'options_check'),
        'id' => 'back_to_jobs_text',
        'std' => 'Back to jobs',
        'type' => 'text');

    $options[] = array(
        'name' => __('Next Events Text', 'options_check'),
        'id' => 'next_events_text',
        'std' => 'Next Events',
        'type' => 'text');

    $options[] = array(
        'name' => __('Past Events Text', 'options_check'),
        'id' => 'past_events_text',
        'std' => 'Past Events',
        'type' => 'text');

    $options[] = array(
        'name' => __('Career Search Box - keyword Placeholder', 'options_check'),
        'id' => 'keyword_placeholder',
        'std' => 'By keyword',
        'type' => 'text');

    $options[] = array(
        'name' => __('Career Search Box - Experience Placeholder', 'options_check'),
        'id' => 'experience_placeholder',
        'std' => 'Select Experience',
        'type' => 'text');

    $options[] = array(
        'name' => __('Career Search Box - Location Placeholder', 'options_check'),
        'id' => 'location_placeholder',
        'std' => 'Select Location',
        'type' => 'text');

    $options[] = array(
        'name' => __('Month Text Selector', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Jan Text', 'options_check'),
        'id' => 'jan_text',
        'std' => 'Jan',
        'type' => 'text');
    $options[] = array(
        'name' => __('Feb Text', 'options_check'),
        'id' => 'feb_text',
        'std' => 'Feb',
        'type' => 'text');
    $options[] = array(
        'name' => __('Mar Text', 'options_check'),
        'id' => 'mar_text',
        'std' => 'Mar',
        'type' => 'text');
    $options[] = array(
        'name' => __('Apr Text', 'options_check'),
        'id' => 'apr_text',
        'std' => 'Apr',
        'type' => 'text');
    $options[] = array(
        'name' => __('May Text', 'options_check'),
        'id' => 'may_text',
        'std' => 'May',
        'type' => 'text');
    $options[] = array(
        'name' => __('Jun Text', 'options_check'),
        'id' => 'jun_text',
        'std' => 'June',
        'type' => 'text');
    $options[] = array(
        'name' => __('Jul Text', 'options_check'),
        'id' => 'jul_text',
        'std' => 'Jul',
        'type' => 'text');
    $options[] = array(
        'name' => __('Aug', 'options_check'),
        'id' => 'aug_text',
        'std' => 'Aug',
        'type' => 'text');
    $options[] = array(
        'name' => __('Sep Text', 'options_check'),
        'id' => 'sep_text',
        'std' => 'Sep',
        'type' => 'text');
    $options[] = array(
        'name' => __('Oct Text', 'options_check'),
        'id' => 'oct_text',
        'std' => 'Oct',
        'type' => 'text');
    $options[] = array(
        'name' => __('Nov Text', 'options_check'),
        'id' => 'nov_text',
        'std' => 'Nov',
        'type' => 'text');
    $options[] = array(
        'name' => __('Dec Text', 'options_check'),
        'id' => 'dec_text',
        'std' => 'Dec',
        'type' => 'text');

    $options[] = array(
        'name' => __('Career Details', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Job Code', 'options_check'),
        'id' => 'job_code',
        'std' => 'Job',
        'type' => 'text');
    $options[] = array(
        'name' => __('Location', 'options_check'),
        'id' => 'location_text',
        'std' => 'Location',
        'type' => 'text');
    $options[] = array(
        'name' => __('Designation', 'options_check'),
        'id' => 'designation_text',
        'std' => 'Designation',
        'type' => 'text');
    $options[] = array(
        'name' => __('Experience', 'options_check'),
        'id' => 'experience_text',
        'std' => 'Experience',
        'type' => 'text');
    $options[] = array(
        'name' => __('Function', 'options_check'),
        'id' => 'function_text',
        'std' => 'Function',
        'type' => 'text');

    $options[] = array(
        'name' => __('Skills', 'options_check'),
        'id' => 'skills_text',
        'std' => 'Skills',
        'type' => 'text');
    $options[] = array(
        'name' => __('Description', 'options_check'),
        'id' => 'description_heading_text',
        'std' => 'Description',
        'type' => 'text');
    $options[] = array(
        'name' => __('Requirements', 'options_check'),
        'id' => 'requirements_text',
        'std' => 'Requirements',
        'type' => 'text');
    $options[] = array(
        'name' => __('Preferences', 'options_check'),
        'id' => 'preferences_text',
        'std' => 'Preferences',
        'type' => 'text');
    $options[] = array(
        'name' => __('Job Responsibilities', 'options_check'),
        'id' => 'job_responsibilities_text',
        'std' => 'Job Responsibilities',
        'type' => 'text');
    $options[] = array(
        'name' => __('Team GlobalLogic (Show this if location Ukraine only.)', 'options_check'),
        'id' => 'job_responsibilities_text1',
        'std' => 'GlobalLogic stands with Ukraine',
        'type' => 'text');

    $options[] = array(
        'name' => __('About Team GlobalLogic (Show this if location Ukraine only.)', 'options_check'),
        'id' => 'job_responsibilities_text2',
        'std' => 'Команда GlobalLogic об\'єднує 26 000 спеціалістів на чотирьох континентах та 14 країнах світу. Україна залишається одним з найбільших центрів розробки GlobalLogic, який ми активно підтримуємо та розвиваємо. Кожна з відкритих позицій на нашому сайті - це можливість долучитися до глобальної команди та побудувати успішну міжнародну кар\'єру. Де б ви не знаходилися зараз. Ось чому опис всіх позицій на сайті GlobalLogic наведено англійською - основною мовою ІТ та мовою міжнародного спілкування у нашій компанії.
        Якщо вам потрібно більше інформації про будь-яку відкриту позицію у GlobalLogic в Україні, напишіть нам на <a href="mailto:join.ukraine@globallogic.com">join.ukraine@globallogic.com</a>.
        Долучайтеся до команди GlobalLogic, щоб створювати важливе разом!',
        'type' => 'editor');
    $options[] = array(
        'name' => __('We Offer', 'options_check'),
        'id' => 'we_offer_text',
        'std' => 'We Offer',
        'type' => 'text');
    $options[] = array(
        'name' => __('About GlobalLogic', 'options_check'),
        'id' => 'about_globalLogic_text',
        'std' => 'About GlobalLogic',
        'type' => 'text');
    $options[] = array(
        'name' => __('Apply Now', 'options_check'),
        'id' => 'apply_now_text',
        'std' => 'Apply Now',
        'type' => 'text');
    $options[] = array(
        'name' => __('Career filter unbale to search criteria messages', 'options_check'),
        'id' => 'unbale_to_search_criteria',
        'std' => '',
        'type' => 'editor');

    $options[] = array(
        'name' => __('Insight Section', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('All ', 'options_check'),
        'id' => 'all',
        'std' => 'All',
        'type' => 'text');
    $options[] = array(
        'name' => __('Filter By', 'options_check'),
        'id' => 'filter_by',
        'std' => 'Filter By',
        'type' => 'text');
    $options[] = array(
        'name' => __('Clear Filters', 'options_check'),
        'id' => 'clear_filters',
        'std' => 'Clear Filters',
        'type' => 'text');
    $options[] = array(
        'name' => __('Learn more', 'options_check'),
        'id' => 'learn_more',
        'std' => 'Learn more',
        'type' => 'text');
    $options[] = array(
        'name' => __('Author', 'options_check'),
        'id' => 'author',
        'std' => 'Author',
        'type' => 'text');
    $options[] = array(
        'name' => __('View all Articles', 'options_check'),
        'id' => 'view_all_articles',
        'std' => 'View all Articles',
        'type' => 'text');
    $options[] = array(
        'name' => __('Top Authors', 'options_check'),
        'id' => 'top_authors',
        'std' => 'Top Authors',
        'type' => 'text');
    $options[] = array(
        'name' => __('View All Authors', 'options_check'),
        'id' => 'view_all_authors',
        'std' => 'View All Authors',
        'type' => 'text');
    $options[] = array(
        'name' => __('Search txt', 'options_check'),
        'id' => 'search_txt',
        'std' => 'Search...',
        'type' => 'text');
    $options[] = array(
        'name' => __('All Categories', 'options_check'),
        'id' => 'all_categories',
        'std' => 'All Categories',
        'type' => 'text');
    $options[] = array(
        'name' => __('All Industries', 'options_check'),
        'id' => 'all_industries',
        'std' => 'All Industries',
        'type' => 'text');
    $options[] = array(
        'name' => __('By txt', 'options_check'),
        'id' => 'by_txt',
        'std' => 'By',
        'type' => 'text');
    $options[] = array(
        'name' => __('Blog category txt', 'options_check'),
        'id' => 'blog_category_txt',
        'std' => 'Blog category',
        'type' => 'text');
    $options[] = array(
        'name' => __('Blog categories txt', 'options_check'),
        'id' => 'blog_categories_txt',
        'std' => 'Blog Categories',
        'type' => 'text');
    $options[] = array(
        'name' => __('View All Categories', 'options_check'),
        'id' => 'view_all_categories_txt',
        'std' => 'View All Categories',
        'type' => 'text');
    $options[] = array(
        'name' => __('Author Txt', 'options_check'),
        'id' => 'author_txt',
        'std' => 'Author',
        'type' => 'text');
    $options[] = array(
        'name' => __('ARTICLE Txt', 'options_check'),
        'id' => 'article_txt',
        'std' => 'ARTICLE',
        'type' => 'text');
    $options[] = array(
        'name' => __('ARTICLES Txt', 'options_check'),
        'id' => 'articles_txt',
        'std' => 'ARTICLES',
        'type' => 'text');
    $options[] = array(
        'name' => __('Blogs By Author', 'options_check'),
        'id' => 'blogs_by_author',
        'std' => 'Blogs By Author',
        'type' => 'text');
    $options[] = array(
        'name' => __('Home', 'options_check'),
        'id' => 'home_txt',
        'std' => 'Home',
        'type' => 'text');
    $options[] = array(
        'name' => __('Insights', 'options_check'),
        'id' => 'insights_txt',
        'std' => 'Insights',
        'type' => 'text');
    $options[] = array(
        'name' => __('Archive', 'options_check'),
        'id' => 'archive_txt',
        'std' => 'Archive',
        'type' => 'text');
    $options[] = array(
        'name' => __('Check out our previous articles', 'options_check'),
        'id' => 'checkout_txt',
        'std' => 'Check out our previous articles',
        'type' => 'text');
    $options[] = array(
        'name' => __('Load Archives', 'options_check'),
        'id' => 'loadarchives_txt',
        'std' => 'Load Archives',
        'type' => 'text');
    $options[] = array(
        'name' => __('Single Insights tag\'s Text', 'options_check'),
        'id' => 'single_insights_tags_text',
        'std' => 'Categories:',
        'type' => 'text');
	$options[] = array(
        'name' => __('Work Together', 'options_check'),
        'id' => 'work_together_txt',
        'std' => '',
        'type' => 'editor');	
    /* carrier 404 setting  */
    $options[] = array(
        'name' => __('Career 404 Setting', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Career Heading Text', 'options_check'),
        'id' => 'career_heading_text',
        'std' => 'We are Sorry!',
        'type' => 'text');
    $options[] = array(
        'name' => __('First Heading', 'options_check'),
        'id' => 'career_first_heading',
        'std' => 'This job has either expired or already been filled. You will be redirected to our list of open positions.',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Second Heading', 'options_check'),
        'id' => 'career_second_heading',
        'std' => 'Thank you for your interest in GlobalLogic!',
        'type' => 'text');
    $options[] = array(
        'name' => __('Carrier submit Button', 'options_check'),
        'id' => 'career_submit_button',
        'std' => 'Ok',
        'type' => 'text');
    /* Accelerator Page */
    $options[] = array(
        'name' => __('Accelerator Page', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Overview', 'options_check'),
        'id' => 'ac_overview',
        'std' => 'Overview',
        'type' => 'text');
    $options[] = array(
        'name' => __('Supported platform', 'options_check'),
        'id' => 'ac_supportedplatform',
        'std' => 'Supported platform',
        'type' => 'text');
    $options[] = array(
        'name' => __('Industries', 'options_check'),
        'id' => 'ac_industries',
        'std' => 'Industries',
        'type' => 'text');
    $options[] = array(
        'name' => __('Technologies/Works well with', 'options_check'),
        'id' => 'ac_work_with',
        'std' => 'Technologies/Works well with',
        'type' => 'text');
    $options[] = array(
        'name' => __('Features', 'options_check'),
        'id' => 'ac_features',
        'std' => 'Features',
        'type' => 'text');
    $options[] = array(
        'name' => __('Resource center', 'options_check'),
        'id' => 'ac_resource',
        'std' => 'Resource center',
        'type' => 'text');
    $options[] = array(
        'name' => __('Employee Head Count', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Argentina Employee Count', 'options_check'),
        'id' => 'argentina_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('Canada Employee Count', 'options_check'),
        'id' => 'canada_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('Croatia Employee Count', 'options_check'),
        'id' => 'croatia_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('Germany Employee Count', 'options_check'),
        'id' => 'germany_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('India Employee Count', 'options_check'),
        'id' => 'india_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('Israel Employee Count', 'options_check'),
        'id' => 'israel_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('Poland Employee Count', 'options_check'),
        'id' => 'poland_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('Slovakia Employee Count', 'options_check'),
        'id' => 'slovakia_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('Sweden Employee Count', 'options_check'),
        'id' => 'sweden_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('Ukraine Employee Count', 'options_check'),
        'id' => 'ukraine_employee_count',
        'std' => '3000+',
        'type' => 'text');
    $options[] = array(
        'name' => __('USA Employee Count', 'options_check'),
        'id' => 'usa_employee_count',
        'std' => '3000+',
        'type' => 'text');
	$options[] = array(
        'name' => __('UK Employee Count', 'options_check'),
        'id' => 'uk_employee_count',
        'std' => '3000+',
        'type' => 'text');	
    $options[] = array(
        'name' => __('Career About Text', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('About Text', 'options_check'),
        'id' => 'career_about_text',
        'std' => 'Country About Text',
        'type' => 'editor');

     // Career Facebook OG Image
    $options[] = array(
        'name' => __('Career OG Image', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Upload career og image for facebook', 'options_check'),
        'id' => 'fb_og_image',
        'std' => '',
        'type' => 'upload');
    $options[] = array(
        'name' => __('Upload career og image for twitter', 'options_check'),
        'id' => 'twitter_og_image',
        'std' => '',
        'type' => 'upload');
    
    // Default Featured Image
    $options[] = array(
        'name' => __('Default Featured Image', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Upload default featured image', 'options_check'),
        'id' => 'gl_dfi_image_id',
        'std' => '',
        'type' => 'upload');
        
        
    /* Job form Page */
    $options[] = array(
        'name' => __('Job Form Page', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('First name', 'options_check'),
        'id' => 'job_firstname',
        'std' => 'First name',
        'type' => 'text');
    $options[] = array(
        'name' => __('Last name', 'options_check'),
        'id' => 'job_lastname',
        'std' => 'Last name',
        'type' => 'text');
    $options[] = array(
        'name' => __('Email', 'options_check'),
        'id' => 'job_email',
        'std' => 'Email',
        'type' => 'text');
    $options[] = array(
        'name' => __('Upload Resume OR Share LinkedIn Profile', 'options_check'),
        'id' => 'job_resume_link',
        'std' => 'Upload Resume / Share LinkedIn Profile',
        'type' => 'text');
    $options[] = array(
        'name' => __('Allow formats for resume', 'options_check'),
        'id' => 'job_resume_support',
        'std' => 'Only .docx, .rtf, .pdf formats allowed to a max size of 5 MB.',
        'type' => 'text');
    $options[] = array(
        'name' => __('OR Text', 'options_check'),
        'id' => 'job_or_support',
        'std' => 'OR',
        'type' => 'text');
    $options[] = array(
        'name' => __('Attach your file here or browse', 'options_check'),
        'id' => 'job_attach_resume',
        'std' => 'Attach your file here or browse',
        'type' => 'text');
    $options[] = array(
        'name' => __('LinkedIn Profile URL', 'options_check'),
        'id' => 'job_linkedin_url',
        'std' => 'LinkedIn Profile URL',
        'type' => 'text');
    $options[] = array(
        'name' => __('Phone', 'options_check'),
        'id' => 'job_phone',
        'std' => 'Phone',
        'type' => 'text');
    $options[] = array(
        'name' => __('Location (City)', 'options_check'),
        'id' => 'job_location',
        'std' => 'Location (City)',
        'type' => 'text');
    $options[] = array(
        'name' => __('How did you hear about this job?', 'options_check'),
        'id' => 'job_coverletter',
        'std' => 'How did you hear about this job?',
        'type' => 'text');
    $options[] = array(
        'name' => __('Email Subject', 'options_check'),
        'id' => 'career_form_email_subject',
        'std' => '',
        'type' => 'text');
    $options[] = array(
        'name' => __('Set up an email template for successfully submitting the Apply Now form', 'options_check'),
        'desc' => __('Email will not be triggered if the email template is empty.'),
        'id' => 'career_form_email_template',
        'std' => '',
        'type' => 'textarea');
    $options[] = array(
        'name' => __('Enter email address', 'options_check'),
        'desc' => __('Enter email address for new candidate registered notification.'),
        'id' => 'new_candidate_registered_email_notification',
        'std' => '',
        'type' => 'text');    
    
    if (get_current_blog_id() == 2 ) {
        $options[] = array(
        'name' => __('Latam (Argentina) Language Consent ', 'options_check'),
        'id' => 'job_latam_argentina_lan_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Latam (Chile) Language Consent ', 'options_check'),
        'id' => 'job_latam_chile_lan_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Latam (Mexico) Language Consent ', 'options_check'),
        'id' => 'job_latam_mexico_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 18 ) {
        $options[] = array(
        'name' => __('Croatia Language Consent', 'options_check'),
        'id' => 'job_hr_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 10 ) {
        $options[] = array(
        'name' => __('Slovakia Language Consent', 'options_check'),
        'id' => 'job_sk_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 14 ) {
        $options[] = array(
        'name' => __('Poland Language Consent', 'options_check'),
        'id' => 'job_pl_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 20 ) {
        $options[] = array(
        'name' => __('Sweden Language Consent', 'options_check'),
        'id' => 'job_se_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 29 ) {
        $options[] = array(
        'name' => __('Spain Language Consent', 'options_check'),
        'id' => 'job_es_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 3 ) {
        $options[] = array(
        'name' => __('Ukraine Language Consent', 'options_check'),
        'id' => 'job_ua_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 26 ) {
        $options[] = array(
        'name' => __('Germany Language Consent', 'options_check'),
        'id' => 'job_de_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 27 ) {
        $options[] = array(
        'name' => __('United Kingdom Language Consent', 'options_check'),
        'id' => 'job_uk_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 19 ) {
        $options[] = array(
        'name' => __('Israel Language Consent', 'options_check'),
        'id' => 'job_il_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 28 ) {
        $options[] = array(
        'name' => __('Japan Language Consent', 'options_check'),
        'id' => 'job_jp_lan_consent',
        'std' => '',
        'type' => 'editor');
    }
    if (get_current_blog_id() == 21 ) {
        $options[] = array(
        'name' => __('India Language Consent', 'options_check'),
        'id' => 'job_in_lan_consent',
        'std' => '',
        'type' => 'editor');
    }

    if (get_current_blog_id() == 1 ) {
        $options[] = array(
        'name' => __('Latam (Argentina) Consent ', 'options_check'),
        'id' => 'job_latam_argentina_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Latam (Chile) Consent ', 'options_check'),
        'id' => 'job_latam_chile_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Latam (Mexico) Consent ', 'options_check'),
        'id' => 'job_latam_mexico_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Croatia Consent', 'options_check'),
        'id' => 'job_croatia_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Germany Consent', 'options_check'),
        'id' => 'job_germany_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Poland Consent', 'options_check'),
        'id' => 'job_poland_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Slovakia Consent', 'options_check'),
        'id' => 'job_slovakia_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Nordic (Sweden) Consent', 'options_check'),
        'id' => 'job_nordic_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Switzerland Consent', 'options_check'),
        'id' => 'job_switzerland_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Romania Consent', 'options_check'),
        'id' => 'job_romania_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('United Kingdom Consent', 'options_check'),
        'id' => 'job_uk_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Spain Consent', 'options_check'),
        'id' => 'job_es_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Ukraine Consent', 'options_check'),
        'id' => 'job_ukraine_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Canada Consent', 'options_check'),
        'id' => 'job_canada_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('United States Consent', 'options_check'),
        'id' => 'job_us_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('Israel Consent', 'options_check'),
        'id' => 'job_israel_consent',
        'std' => '',
        'type' => 'editor');  
        $options[] = array(
        'name' => __('Japan Consent', 'options_check'),
        'id' => 'job_japan_consent',
        'std' => '',
        'type' => 'editor');
        $options[] = array(
        'name' => __('India Consent', 'options_check'),
        'id' => 'job_india_consent',
        'std' => '',
        'type' => 'editor');
    }

	$options[] = array(
        'name' => __('Locations Page', 'options_check'),
        'type' => 'heading');

        $options[] = array(
            'name' => __('Hero Title', 'options_check'),
            'id' => 'locations_hero_title',
            'std' => '',
            'type' => 'textarea');  

        $options[] = array(
            'name' => __('Hero Description', 'options_check'),
            'id' => 'locations_hero_description',
            'std' => '',
            'type' => 'textarea');  


	$options[] = array(
        'name' => __('Lets Work Together Form', 'options_check'),
        'type' => 'heading');
    $options[] = array(
        'name' => __('Title', 'options_check'),
        'id' => 'together_title',
        'std' => "Let’s Work Together",
        'type' => 'text');
	$options[] = array(
        'name' => __('Color', 'options_check'),
        'id' => 'together_color',
        'std' => '#e6e7e8',
        'type' => 'text');
	$options[] = array(
        'name' => __('Form Id', 'options_check'),
        'id' => 'together_form_id',
        'std' => '2406',
        'type' => 'text');
		
    return $options;
}
